name: Deploy React + PHP to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies (React)
      run: |
        cd frontend
        npm install

    - name: Build React app
      run: |
        cd frontend
        npm run build

    - name: Copy PHP + React build to release folder
      run: |
        mkdir release
        cp -r backend/* release/
        cp -r frontend/build/* release/

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: release

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: facturaelectronica  # <-- cambia esto por el nombre real de tu Web App en Azure
        slot-name: Production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: release
